# Generated by Django 5.1.2 on 2024-10-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisementmodel',
            old_name='car_additional_describe',
            new_name='car_additional_description',
        ),
    ]
