# Generated by Django 5.1.2 on 2024-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='photo',
            field=models.ImageField(blank=True, default=1, upload_to='photo_adv'),
            preserve_default=False,
        ),
    ]
