# Generated by Django 5.1.2 on 2024-10-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticadvertisementmodel',
            options={},
        ),
    ]
