# Generated by Django 5.1.2 on 2024-10-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='statistic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='advertisement.statisticadvertisementmodel'),
        ),
    ]
