# Generated by Django 5.1.2 on 2024-10-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementmodel',
            name='photo_count',
        ),
    ]
