# Generated by Django 5.1.2 on 2024-10-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statisticadvertisementmodel',
            name='car_avg_price_in_region',
        ),
        migrations.RemoveField(
            model_name='statisticadvertisementmodel',
            name='car_avg_price_in_uk',
        ),
    ]
