# Generated by Django 5.1.2 on 2024-10-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_remove_advertisementmodel_edit_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='edit_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
