# Generated by Django 5.1.2 on 2024-10-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_rename_car_additional_describe_advertisementmodel_car_additional_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementmodel',
            name='edit_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
