# Generated by Django 5.1.2 on 2024-10-27 17:27

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_remove_statisticadvertisementmodel_car_avg_price_in_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticadvertisementmodel',
            name='last_view_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 27, 17, 27, 6, 8463, tzinfo=datetime.timezone.utc)),
        ),
    ]
