# Generated by Django 5.1.2 on 2024-10-18 14:02

from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisementmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementmodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=core.services.file_service.FileService.upload_file),
        ),
    ]
