# Generated by Django 5.1.2 on 2024-10-27 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_statisticadvertisementmodel_last_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticadvertisementmodel',
            name='last_view_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
