# Generated by Django 5.1.2 on 2024-10-27 17:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_alter_statisticadvertisementmodel_last_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticadvertisementmodel',
            name='last_view_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
