services:
  app:
    build:
      context: .
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    working_dir: /app
    ports:
      - "8888:8000"
    restart: on-failure
    command: >
      sh -c "python manage.py wait_db && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ./postgresql_db:/var/lib/postgresql
    ports:
      - "5434:5432"
    restart: on-failure

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./backend/staticfiles:/usr/share/nginx/doc
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: on-failure

  redis:
    image: redis:alpine

  celery:
    build:
      context: .
    volumes:
      - ./backend:/app
    env_file:
      - .env
    restart:
      on-failure
    command: >
      sh -c "celery -A configs worker -l info -B"
