# Generated by Django 5.1.2 on 2024-10-29 10:37

import django.core.validators
from django.db import migrations, models

import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_brand', models.CharField(choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroën', 'Citroën'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Genesis', 'Genesis'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infinity', 'Infinity'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Maserati', 'Maserati'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Pagani', 'Pagani'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('RAM', 'RAM'), ('Renault', 'Renault'), ('Rolls-Royce', 'Rolls-Royce'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Škoda', 'Škoda'), ('Seat', 'Seat'), ('Smart', 'Smart'), ('SsangYong', 'SsangYong')], max_length=20)),
                ('car_model', models.CharField(max_length=20)),
                ('vin_code', models.CharField(unique=True)),
                ('car_body_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Wagon', 'Wagon'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Pickup', 'Pickup'), ('Van', 'Van'), ('Minivan', 'Minivan'), ('Crossover', 'Crossover'), ('Sport car', 'Sport car'), ('Limousine', 'Limousine'), ('Other', 'Other')], max_length=15)),
                ('car_gear_type', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic'), ('CVT', 'Continuously Variable Transmission'), ('DCT', 'Dual-Clutch Transmission'), ('Tiptronic', 'Tiptronic'), ('Sport shift', 'Sport shift'), ('Other', 'Other')], max_length=20)),
                ('car_fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Plug-in Hybrid', 'Plug-in Hybrid'), ('Natural Gas', 'Natural Gas'), ('LPG', 'Liquefied Petroleum Gas'), ('Biodiesel', 'Biodiesel'), ('Ethanol', 'Ethanol'), ('Other', 'Other')], max_length=30)),
                ('car_mileage', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('car_engine_displacement', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('car_drivetrain', models.CharField(choices=[('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive'), ('AWD', 'All-Wheel Drive'), ('4WD', 'Four-Wheel Drive')], max_length=20)),
                ('car_year', models.IntegerField(error_messages="Car's year cannot be less than 1950 and more than 2024 ", validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2024)])),
                ('car_country_origin', django_countries.fields.CountryField(max_length=2)),
                ('car_accident_history', models.TextField()),
            ],
            options={
                'db_table': 'car',
                'ordering': ['id'],
            },
        ),
    ]
