# Generated by Django 5.1.2 on 2024-11-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('premium', 'premium'), ('basic', 'basic')], default='basic', max_length=7),
        ),
    ]
