# Generated by Django 5.1.2 on 2024-10-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role_type',
            field=models.CharField(choices=[('seller', 'seller'), ('buyer', 'buyer'), ('other', 'other')], max_length=6),
        ),
    ]
