# Generated by Django 5.1.2 on 2024-10-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
