from django.db import models


class CarDrivetrainTypeChoices(models.TextChoices):
    FRONT_WHEEL = "FWD"
    REAR_WHEEL = "RWD"
    ALL_WHEEL = "AWD"
    FOUR_WHEEL = "4WD"


class CarBodyTypeChoices(models.TextChoices):
    HATCHBACK = "Hatchback"
    SEDAN = "Sedan"
    COUPE = "Coupe"
    WAGON = "Wagon"
    SUV = "SUV"
    CONVERTIBLE = "Convertible"
    PICKUP = "Pickup"
    VAN = "Van"
    MINIVAN = "Minivan"
    CROSSOVER = "Crossover"
    SPORT_CAR = "Sport car"
    LIMOUSINE = "Limousine"
    OTHER = "Other"


class CarGearTypeChoices(models.TextChoices):
    MANUAL = "Manual"
    AUTOMATIC = "Automatic"
    SEMI_AUTOMATIC = "Semi-Automatic"
    CVT = "CVT"
    DCT = "DCT"
    TIPTRONIC = "Tiptronic"
    SPORT_SHIFT = "Sport shift"
    OTHER = "Other"


class CarFuelTypeChoices(models.TextChoices):
    PETROL = "Petrol"
    DIESEL = "Diesel"
    ELECTRIC = "Electric"
    HYBRID = "Hybrid"
    PLUG_IN_HYBRID = "Plug-in Hybrid"
    NATURAL_GAS = "Natural Gas"
    LIQUEFIED_PETROLEUM_GAS = "LPG"
    BIODIESEL = "Biodiesel"
    ETHANOL = "Ethanol"
    OTHER = "Other"


class CarBrandChoices(models.TextChoices):
    ACURA = "Acura"
    ALFA_ROMEO = "Alfa Romeo"
    ASTON_MARTIN = "Aston Martin"
    AUDI = "Audi"
    BENTLEY = "Bentley"
    BMW = "BMW"
    BUGATTI = "Bugatti"
    BUICK = "Buick"
    CADILLAC = "Cadillac"
    CHEVROLET = "Chevrolet"
    CHRYSLER = "Chrysler"
    CITROEN = "Citroën"
    DODGE = "Dodge"
    FERRARI = "Ferrari"
    FIAT = "Fiat"
    FORD = "Ford"
    GENESIS = "Genesis"
    GMC = "GMC"
    HONDA = "Honda"
    HYUNDAI = "Hyundai"
    INFINITY = "Infinity"
    JAGUAR = "Jaguar"
    JEEP = "Jeep"
    KIA = "Kia"
    LAMBORGHINI = "Lamborghini"
    LAND_ROVER = "Land Rover"
    LEXUS = "Lexus"
    MASERATI = "Maserati"
    MAZDA = "Mazda"
    MCLAREN = "McLaren"
    MERCEDES_BENZ = "Mercedes-Benz"
    MINI = "Mini"
    MITSUBISHI = "Mitsubishi"
    NISSAN = "Nissan"
    PAGANI = "Pagani"
    PEUGEOT = "Peugeot"
    PORSCHE = "Porsche"
    RAM = "RAM"
    RENAULT = "Renault"
    ROLLS_ROYCE = "Rolls-Royce"
    SUBARU = "Subaru"
    SUZUKI = "Suzuki"
    TESLA = "Tesla"
    TOYOTA = "Toyota"
    VOLKSWAGEN = "Volkswagen"
    VOLVO = "Volvo"
    SKODA = "Škoda"
    SEAT = "Seat"
    SMART = "Smart"
    SSANGYONG = "SsangYong"
