# from django.db import models
#
#
# class CarModel(models.Model):
#     class Meta:
#         db_table = "car"
#         ordering = ["id"]
#
#     car_brand = ...
#     car_model = ...
#     vin_code = ...
#     car_body_type = ...
#     car_gear_type = ...
#     car_fuel_type = ...
#     car_mileage = ...
#     car_engine_displacement = ...
#     car_drivetrain = ...
#     car_year = ...
#     car_country_origin = ...
#     car_accident_history = ...
