from django.db import models

from core.models import BaseModel


class AdvertisementModel(BaseModel):
    class Meta:
        db_table = "advertisement"
        ordering = ["id"]

    general_views = ...
    day_views = ...
    week_views = ...
    month_views = ...
    region_avg_car_price = ...
    country_avg_car_price = ...


class StatisticAdvertisementModel(models.Model):
    class Meta:
        db_table = "statistic_advertisement"
        ordering = ["id"]

    seller = ...
    car = ...
    price = ...
    currency = ...
    sale_location = ...
    photo_count = ...
    is_active = ...
    car_additional_describe = ...
    statistic = ...
